# Generated by Django 4.2.7 on 2023-11-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0002_alter_post_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор'},
        ),
    ]
