# Generated by Django 5.0.1 on 2024-02-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0003_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
