# Generated by Django 4.2.7 on 2023-11-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
